config/routes.rb
SwDcOct::Application.routes.draw do
  resources :event_volunteers

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get "static_pages/home"

  get "static_pages/help"
  get "static_pages/search"

  resources :events

  resources :users

  resources :organizations

  resources :events
  root :to => 'static_pages#home'

end

app/models/event_volunteer.rb
class EventVolunteer < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  attr_accessible :event_id, :showed_up, :user_id
  validates_uniqueness_of :event_id, :scope => :user_id
end

app/controllers/event_volunteers_controller.rb
class EventVolunteersController < ApplicationController
  # GET /event_volunteers
  # GET /event_volunteers.json
  def index
    @event_volunteers = EventVolunteer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_volunteers }
    end
  end

  # GET /event_volunteers/1
  # GET /event_volunteers/1.json
  def show
    @event_volunteer = EventVolunteer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_volunteer }
    end
  end

  # GET /event_volunteers/new
  # GET /event_volunteers/new.json
  def new
    @event_volunteer = EventVolunteer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_volunteer }
    end
  end

  # GET /event_volunteers/1/edit
  def edit
    @event_volunteer = EventVolunteer.find(params[:id])
  end

  # POST /event_volunteers
  # POST /event_volunteers.json
  def create
    @event_volunteer = EventVolunteer.new(params[:event_volunteer])

    respond_to do |format|
      if @event_volunteer.save
        format.html { redirect_to :back, notice: 'You have been signed up!' }
        format.json { render json: @event_volunteer, status: :created, location: @event_volunteer }
      else
        format.html { render action: "new" }
        format.json { render json: @event_volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_volunteers/1
  # PUT /event_volunteers/1.json
  def update
    @event_volunteer = EventVolunteer.find(params[:id])

    respond_to do |format|
      if @event_volunteer.update_attributes(params[:event_volunteer])
        format.html { redirect_to @event_volunteer, notice: 'Event volunteer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_volunteers/1
  # DELETE /event_volunteers/1.json
  def destroy
    @event_volunteer = EventVolunteer.find(params[:id])
    @event_volunteer.destroy

    respond_to do |format|
      format.html { redirect_to event_volunteers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/event_volunteers_helper.rb
module EventVolunteersHelper
end

app/views/event_volunteers/_form.html.erb
<%= form_for(@event_volunteer) do |f| %>
  <% if @event_volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_volunteer.errors.count, "error") %> prohibited this event_volunteer from being saved:</h2>

      <ul>
      <% @event_volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :showed_up %><br />
    <%= f.check_box :showed_up %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_volunteers/edit.html.erb
<h1>Editing event_volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_volunteer %> |
<%= link_to 'Back', event_volunteers_path %>

app/views/event_volunteers/index.html.erb
<h1>Listing event_volunteers</h1>

<table>
  <tr>
    <th>Event</th>
    <th>User</th>
    <th>Showed up</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_volunteers.each do |event_volunteer| %>
  <tr>
    <td><%= event_volunteer.event_id %></td>
    <td><%= event_volunteer.user_id %></td>
    <td><%= event_volunteer.showed_up %></td>
    <td><%= link_to 'Show', event_volunteer %></td>
    <td><%= link_to 'Edit', edit_event_volunteer_path(event_volunteer) %></td>
    <td><%= link_to 'Destroy', event_volunteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event volunteer', new_event_volunteer_path %>

app/views/event_volunteers/new.html.erb
<h1>New event_volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', event_volunteers_path %>

app/views/event_volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_volunteer.event_id %>
</p>

<p>
  <b>User:</b>
  <%= @event_volunteer.user_id %>
</p>

<p>
  <b>Showed up:</b>
  <%= @event_volunteer.showed_up %>
</p>


<%= link_to 'Edit', edit_event_volunteer_path(@event_volunteer) %> |
<%= link_to 'Back', event_volunteers_path %>