config/routes.rb
SwDcOct::Application.routes.draw do
  resources :event_volunteers

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get "static_pages/home"

  get "static_pages/help"
  get "static_pages/search"

  resources :events

  resources :users

  resources :organizations

  resources :events
  root :to => 'static_pages#home'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :events
  has_and_belongs_to_many :organizers, class_name: 'User'
  attr_accessible :name, :ein, :email, :address, :description, :phone, :website, :image_path
  before_validation :clean_ein
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :ein, presence: true, uniqueness: true, format: { with: /\A\d{9}\z/ }
  validates :organizers, presence: true

  def to_s
    name
  end

private

  def clean_ein
    self[:ein] = ein.to_s.gsub(/\D/, '')
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])
    @organization.organizers << current_user

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ein %><br />
    <%= f.text_field :ein %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br />
    <%= f.text_field :image_path %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Ein</th>
    <th>Website</th>
    <th></th>
    <% if @organizations.any? { |o| o.organizers.include? current_user } %>
      <th></th>
      <th></th>
    <% end %>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= organization.description %></td>
    <td><%= organization.address %></td>
    <td><%= organization.phone %></td>
    <td><%= organization.email %></td>
    <td><%= organization.ein %></td>
    <td><%= organization.website %></td>
    <td><%= link_to 'Show', organization %></td>
    <% if organization.organizers.include? current_user %>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_user %>
  <%= link_to 'New Organization', new_organization_path %>
<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Description:</b>
  <%= @organization.description %>
</p>

<p>
  <b>Address:</b>
  <%= @organization.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @organization.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @organization.email %>
</p>

<p>
  <b>Ein:</b>
  <%= @organization.ein %>
</p>

<p>
  <b>Website:</b>
  <%= @organization.website %>
</p>

<% if @organization.organizers.include?(current_user) %>
  <%= link_to "New event", new_event_path(event: {organization_id: @organization.id}) %> |
  <%= link_to 'Edit', edit_organization_path(@organization) %>
<% end %>

<%= link_to 'Back', organizations_path %>