config/routes.rb
SwDcOct::Application.routes.draw do
  resources :event_volunteers

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get "static_pages/home"

  get "static_pages/help"
  get "static_pages/search"

  resources :events

  resources :users

  resources :organizations

  resources :events
  root :to => 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "ALLtruism", root_path %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "Events", events_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Organizations", organizations_path %></li>
          <li class="divider"></li>
          <% if current_user %>
            <li><%= link_to "Sign out", signout_path, :method => 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>

    <div class="row">
      <%= yield %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>